version: "3.9"

services:
  dev:
    container_name: calundula_dev
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
    ports:
      - 8000:8000
    volumes:
      - .:/calendula/
    depends_on:
      - db
  db:
    container_name: calendula_db
    image: postgres:15.2-alpine
    volumes:
      - calendula_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
       - "5432:5432"
        
volumes:
  calendula_data:
